// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGir3bj87tXee_kVjR5HxyVIzaSvl0Sbo',
    appId: '1:562796003130:web:2a100c3d8d9b5c71629a03',
    messagingSenderId: '562796003130',
    projectId: 'cicd-example-4d8df',
    authDomain: 'cicd-example-4d8df.firebaseapp.com',
    storageBucket: 'cicd-example-4d8df.appspot.com',
    measurementId: 'G-5M7TYMQHBN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJq9cqrRLGAsLU09ZeLw0_lMiyG7htK1o',
    appId: '1:562796003130:android:fc283cbb92153287629a03',
    messagingSenderId: '562796003130',
    projectId: 'cicd-example-4d8df',
    storageBucket: 'cicd-example-4d8df.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIwT8e4VOff64vqEtJhDJFwNMh_fciuJ4',
    appId: '1:562796003130:ios:338dff512fda39f2629a03',
    messagingSenderId: '562796003130',
    projectId: 'cicd-example-4d8df',
    storageBucket: 'cicd-example-4d8df.appspot.com',
    iosClientId:
        '562796003130-lq6ca0p4mmg2nosncc0231h0ldop9tn2.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterCicd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIwT8e4VOff64vqEtJhDJFwNMh_fciuJ4',
    appId: '1:562796003130:ios:338dff512fda39f2629a03',
    messagingSenderId: '562796003130',
    projectId: 'cicd-example-4d8df',
    storageBucket: 'cicd-example-4d8df.appspot.com',
    iosClientId:
        '562796003130-lq6ca0p4mmg2nosncc0231h0ldop9tn2.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterCicd',
  );
}
