name: Build and test

on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main
  workflow_dispatch:

# Declare default permissions as read only.
permissions: read-all

jobs:
  build:
    name: Build ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        target: [iOS, Android]
        include:
          - os: macos-latest
            target: iOS
            build_target: ios --no-codesign
            build_path: build/ios/iphoneos
            asset_extension: .app
            appId: com.example.flutterCicd
          - os: ubuntu-latest
            target: Android
            build_target: apk
            build_path: build/app/outputs/flutter-apk
            asset_extension: .apk
            appId: com.example.flutter_cicd
    steps:
      # Set up Flutter.
      - name: Clone Flutter repository with master channel
        uses: subosito/flutter-action@d8687e6979e8ef66d2b2970e2c92c1d8e801d7bf
        with:
          channel: master
      - run: flutter config --enable-macos-desktop
      - run: flutter doctor -v
      - name: Checkout code
        uses: actions/checkout@d171c3b028d844f2bf14e9fdec0c58114451e4bf
      - run: flutter pub get
      - run: flutter build ${{ matrix.target }}
      - name: Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1.2.1
        with:
          appId: ${{ matrix.appId }}
          token: ${{ secrets.FIREBASE_TOKEN }}
          groups: beta-testers
          file: app/build/outputs/apk/release/app-release-unsigned.apk
