name: Build and deploy Android

on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main
  workflow_dispatch:

# Declare default permissions as read only.
permissions: read-all

jobs:
  build:
    name: Build Android
    runs-on: ubuntu-latest
    steps:

      # Set up Flutter.
      - name: Clone Flutter repository with master channel
        uses: subosito/flutter-action@v2
        with:
          channel: master
      - run: flutter doctor -v

      # Set up java
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Flutter get packages, analyse, format, build
      - run: make get
      - run: make lint
      - run: make format
      - run: flutter build apk

      # Distribute app
      - name: Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.ANDROID_APP_ID }}
          token: ${{ secrets.FIREBASE_TOKEN }}
          groups: beta-testers
          file: build/app/outputs/flutter-apk/app-release.apk